---
- name: start zookeeper
  hosts: pangu-zookeeper
  sudo: True
  tasks:
    - supervisorctl: name=zookeeper state=started

- name: start redis
  hosts: pangu-redis
  sudo: True
  tasks:
    - service: name=redis state=started enabled=yes

- name: start storm
  hosts: pangu-storm
  sudo: True
  tasks:  
    - supervisorctl: name=nimbus state=started
      when: storm_nimbus_enabled
    - supervisorctl: name=supervisor state=started
      when: storm_supervisor_enabled
